apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: icharles
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
           name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/icharles-harbor-project/app@sha256:8a49cd4ca787ad67fce971ca04d14c4cefeeac3c8ded5665c81971d57672bd60
        ports:
        - containerPort: 5000
