apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: icharles
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/icharles-harbor-project/db@sha256:b850f1ea78f41608136332c7a8a3c39674373d76cad2ad73dc9f316021a97313
        ports:
        - containerPort: 5432